export const siteConfig = {
  title: '咕咚的小站',
  description:
    '一个以内容为中心的个人博客，适合写随笔、笔记、项目记录和长期积累。',
  url: 'https://boke-git.pages.dev',
  lang: 'zh-CN',
  locale: 'zh-CN',
  author: '咕咚',
  email: '',
  tagline: '先安静写作，再按需扩展的博客起点。',
  location: 'GitHub + Cloudflare Pages',
  nav: [
    { href: '/', label: '首页' },
    { href: '/blog/', label: '归档' },
    { href: '/search/', label: '搜索' },
    { href: '/about/', label: '关于' },
    { href: '/rss.xml', label: 'RSS' },
  ],
  social: [],
  comments: {
    enabled: false,
    repo: '',
    repoId: '',
    category: 'General',
    categoryId: '',
    mapping: 'pathname',
    strict: '0',
    reactionsEnabled: '1',
    emitMetadata: '0',
    inputPosition: 'top',
    lang: 'zh-CN',
    theme: 'light',
  },
};
